version: '3.8'

services:
  ecommerce_container:
    image: liza-mauhay/zalando-ecommerce-springboot:1.0.0-SNAPSHOT
    container_name: ecommerce_container
    ports:
      - 8081:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://${DOCKER_DB_HOST}/${DOCKER_DB_NAME}${DOCKER_DB_PROPERTIES}
      SPRING_DATASOURCE_USERNAME: ${DOCKER_DB_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${DOCKER_DB_PASSWORD}
      api.key: ${DOCKER_API_KEY}
      jwt.key: ${JWT_KEY}
      jwt.issuer: ${JWT_ISSUER}
    depends_on:
      - mysql_container
    networks:
      ecommerce-mysql-net:

  mysql_container:
    image: mysql:8.1.0
    container_name: mysql_container
    environment:
      DATABASE_HOST: ${DOCKER_CONTAINER_HOST}
      DATABASE_PORT: 3306
      MYSQL_ROOT_PASSWORD: ${DOCKER_CONTAINER_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DOCKER_DB_NAME}
      MYSQL_USER: ${DOCKER_DB_USERNAME}
      MYSQL_PASSWORD: ${DOCKER_DB_PASSWORD}
    ports:
      - 3306:3306
    networks:
      ecommerce-mysql-net:

networks:
  ecommerce-mysql-net:
    driver: bridge